version: '3.9'

# Services
Services: FPM Service
php:
 image: wobdy/php:latest
 volumes:
 - ./php:/var/www/html
   depends_on:
   -mariadb
   # Nginx Service
   nginx
   image: nginx:latest
   ports:
   - 88:80
   links:
   - 'php'
   volumes:
   - './html:/var/www/html'
   - './docker/nginx/conf.d:/etc/nginx/conf.d'
   depends_on:
   -  php
   # MariaDB Service
   mariadb:
   image: mysql:latest  
   environment:
   MYSQL_DATABASE+: ${DB_SCHEMA_NAME}
   MYSQL_USER+: ${DB_USER}
   MYSQL_PASSWORD+: ${DB_PASSWORD}
   MYSQL_ROOT_PASSWORD+: ${DB_ROOT_PASSWORD}
   ports:
   - 3306:3306

   # php myadmin is an external image
   phpmyadmin:
   image: phpmyadmin/phpmyadmin
   environment:
   PMA_HOST: ${DB_HOST}
   PMA_USER: ${DB_USER}
   PMA_PASSWORD: ${DB_PASSWORD}
   ports:
   - "1088:80"

   # Volumes
   volumes:
   mysqldata:
# PHP 